### ISSUE TITLE
BOSH director fails to identify VPC in a GCP project

### ISSUE THREAD

**Issue by nvprakashreddy** [cloudfoundry/bosh#1962]
While installing BOSH director for PKS, observing following error

**Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'stemcell-91dae2a6-3417-407d-6ccf-6554e242c48d':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating VM: Network 'agent-pks-virt-net' does not exist in project 'pks-agent-test': \u003cnil cause\u003e","ok_to_retry":false}
Exit code 1**

Please look into it ASAP.

**Comment by nvprakashreddy** [comment]
Issue is resolved.

**Comment by vijaybujula** [comment]
Happened to what version of bosh/cpi? I am still getting same error on a shared VPC/Subnet with bosh 268.5.0/ CPI 29.

**Comment by nvprakashreddy** [comment]
Not remembering the bosh version, i remember the issue was created due to incorrect configurations in bosh server.

**Comment by vijayb47** [comment]
fyi.. any facing the same issue. If you are deploying director into a shared VPC, add xpn_host_project_id property in cpi.yml 
and supply value to it. Otherwise, bosh tries to find that n/w in current GCP project.

- type: replace
  path: /networks/name=default/subnets/0/cloud_properties?
  value:
    xpn_host_project_id: ((xpn_host_project_id))
    network_name: ((network))
    subnetwork_name: ((subnetwork))
    ephemeral_external_ip: false
    tags: ((tags))
