### ISSUE TITLE
cloud-config provisionned bosh variables wont update from credhub on bosh re-deploy

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh#2046]
**Describe the bug**

Expecting bosh deploy to refresh variables from credhub if changed. We get http 404 error for variables injected from cloud-config (networks cloud-properties)

**To Reproduce**
Steps to reproduce the behavior (example):

1. define a cloud-config network, with a property from credhub ((xxx))
2. populate the property to credhub
3. bosh deploy a deployment using the cloud-config network
4. now delete the credhub var with credhub cli
5 recreate the credhub var with credhub cli, same name, same value
6 bosh deploy the deployment

You get this error
```
 Failed to find variable '/secrets/intranet_interco_ips_net_id' with id '0651645a-750a-4948-aa5f-0c02919bd264' from config server: HTTP Code '404'
```
see slack discussion https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1536048224000100

**Expected behavior**
I expect the bosh deploy to lookup credhub var per name and retrieve current value

**Logs**
Logs are always helpful! Add logs to help explain your problem.

**Versions (please complete the following information):**
 - Infrastructure: openstack
 - BOSH version 266.10.0

**Deployment info:**
If possible, share your (redacted) manifest and any ops files used to deploy
BOSH or any other releases on top of BOSH.

If you used any deployment strategy it'd be helpful to point it out and share as
much about it as possible (e.g.  bosh-deployment, PCF, genesis, spiff, etc)

**Additional context**

cc @pivotal-jamil-shamy

**Comment by pivotal-jamil-shamy** [comment]
thanks @poblin-orange for reporting this.

I was able to reproduce the issue. Looks like there is a problem with how cloud-config variables are being versioned in the director.

**Comment by dpb587-pivotal** [comment]
Closing - it looks like this was fixed since [v268.1.0](https://github.com/cloudfoundry/bosh/releases/tag/v268.1.0).

**Comment by poblin-orange** [comment]
@dpb587 @pivotal-jamil-shamy 

Hello, i just tested with bosh 268.6, still having issues with cloud-config properties with credhub reference. Should i open another issue ?
